### ISSUE TITLE
Russian Roulette bug

### ISSUE THREAD

**Issue by Tuberculosis-FP** [azalty/sm-hosties-plus#7]
**Describe the bug**
In Russian Roulette, you can start the LR but whoever has the first shot, and takes their shot, will be slain for cheating for using deagle

>>> tuberculosis foreplay has taken his shot.
>>> tuberculosis foreplay was slain for attacking basketball made of used needles with deagle during LR.

I would just disable this LR's anti cheat but that does not seem to be an option.

**Error logs**
None.

---

https://github.com/azalty/sm-hosties-plus/assets/137737706/75be9011-6b76-4156-9152-05874cea43cf

Hope you enjoy the unregistered hypercam 2 15fps :)))

**Comment by azalty** [comment]
Thanks for the bug report. Seems exclusive to CS:S as I didn't encounter this bug in CS:GO.

I will investigate it. The video is much appreciated :)

**Comment by azalty** [comment]
I sent you a debugging version on discord so we can figure out the problem, because I don't find any obvious bug

**Comment by azalty** [comment]
More CS:S testers required.

**Comment by azalty** [comment]
Seems bugged in cs:s, same thing on someone else's cs:s server

I have new clues about the origin of the bug and I'll investigate further but it seems like a hard thing to understand

**Comment by azalty** [comment]
Should be fixed in 5.1.0 BETA 3, testing required :)

**Comment by azalty** [comment]
The fix is out on the stable version 5.1.0

Please re-open if it still happens.
